Einstore/EinstoreAdmin

src/parts/Layout.tsx
=> Dropzone: disable click

src/components/Login.tsx, src/components/button.sass, src/parts/Auth.tsx, src/parts/login.sass
Closes #4 
Closes #5 
Closes #6
=> Auth view styling

src/components/Overview.tsx
=> better note about missing apps

package-lock.json, package.json, src/declare.d.ts, src/parts/Layout.tsx
=> Revert Dropzone version

src/components/card.sass
=> Add spacing for invite form

src/App.tsx, src/components/TeamName.tsx, src/components/TeamTag.tsx
=> Implement switching team icon in header

src/components/Overview.tsx
=> Copy: empty state on overview

src/parts/systemSettings.sass
=> System icon border-radius

src/connector/Einstore.ts, src/parts/Sidebar.tsx
=> System settings link

src/parts/layout.sass
=> always visible sidebar on 1600px+

src/components/Overview.tsx, src/components/cardList.js, src/connector/Einstore.ts, src/connector/Model/Overview.ts, src/parts/appBuilds.js, src/parts/appDetail.js
`Apps > Clusters > Teams` => `Builds > Apps > Teams`
=> Update naming things - no more clusters

src/components/cardInfo.js, src/components/cardInfo.sass
=> CardInfo PM rendered as other info messages

src/components/SecurityOverview.sass
=> Fix SecurityOverview alerts to block

package.json, src/components/cardInfo.js, src/components/cardItem.js, src/components/cardList.js, src/parts/appBuilds.js, src/parts/appDetail.js, src/utils/prettyDate.ts
https://github.com/Einstore/Einstore/issues/126
=> Date formatting

src/components/AddApiKey.tsx, src/components/Login.tsx, src/parts/Auth.tsx, src/parts/account.js, src/utils/showMessage.ts
https://github.com/Einstore/Einstore/issues/137
=> unify error message handling and handle api error response

src/components/Overview.tsx, src/utils/browserStorage.ts
https://github.com/Einstore/Einstore/issues/82
=> make browser remember last sorting type and direction

src/App.tsx, src/app.sass, src/components/button.sass, src/parts/Auth.tsx
https://github.com/Einstore/Einstore/issues/52
=> registration

src/parts/layout.sass
https://github.com/Einstore/Einstore/issues/143
=> show menu when screen size is greater than 1200

src/App.tsx, src/components/notice.sass, src/components/teamMember.js, src/parts/Sidebar.tsx, src/parts/team.js
https://github.com/Einstore/Einstore/issues/53
=> Team&members - show all users when no team is selected

src/parts/SystemSettings.tsx
https://github.com/Einstore/Einstore/issues/141
=> WIP: #141 fix image upload in system settings
